[package]
name = "httpsig"
version = "0.1.0-alpha.0"
authors = ["Walfie <walfington@gmail.com>"]
edition = "2018"

[dependencies]
openssl = "0.10"
http = "0.1"
base64 = "0.10"

[dev-dependencies]
httparse = "1.3"
